# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EAS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ProtocolBuffers-Swift'
  # Pods for EAS

  target 'EASTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EAS WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EAS WatchKit App

end

target 'EAS WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EAS WatchKit Extension

end
