#!/bin/sh

IMAGE=""
if [ -e $PWD/CMakeLists.txt ]; then
    IMAGE="oreilly/rac-native-devel"
elif [ -e $PWD/build.sbt ]; then
    IMAGE="oreilly/rac-jvm-devel"
fi

docker run -t -i -v $PWD:/var/src $IMAGE /bin/bash
